name: lazy
description: A library adding lazy evaluation to Dart.
version: 1.0.0-preview
repository: https://github.com/mateusfccp/lazy
issue_tracker: https://github.com/mateusfccp/lazy/issues

environment:
  sdk: '>=3.3.0 <4.0.0'

dev_dependencies:
  test: ^1.25.2
